import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// ============================================
// Concierge Premium UI Components
// "1 Melhor + 3 Alternativas" Pattern
// ============================================
import { useState } from 'react';
export const BestChoiceCard = ({ choice, baseFood, onSelect }) => {
    return (_jsxs("div", { className: "relative overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-50 to-emerald-100 border-2 border-emerald-200 p-6 shadow-lg", children: [_jsx("div", { className: "absolute top-4 right-4", children: _jsxs("span", { className: "inline-flex items-center gap-1 rounded-full bg-emerald-600 px-3 py-1 text-xs font-semibold text-white", children: [_jsx("svg", { className: "h-3 w-3", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z", clipRule: "evenodd" }) }), "Melhor agora"] }) }), _jsxs("div", { className: "pr-24", children: [_jsxs("p", { className: "text-sm text-emerald-600 font-medium mb-1", children: ["Substituindo ", baseFood] }), _jsx("h3", { className: "text-2xl font-bold text-gray-900 mb-2", children: choice.food }), _jsxs("p", { className: "text-lg text-gray-700 mb-4", children: [_jsxs("span", { className: "font-semibold", children: [choice.grams, "g"] }), _jsx("span", { className: "text-gray-400 mx-2", children: "\u2022" }), _jsxs("span", { children: [choice.kcal, " kcal"] })] })] }), _jsx("p", { className: "text-gray-600 mb-4 leading-relaxed", children: choice.why }), _jsxs("div", { className: "flex gap-4 text-sm text-gray-500 mb-4", children: [_jsxs("span", { children: ["C: ", choice.macros.carb_g, "g"] }), _jsxs("span", { children: ["P: ", choice.macros.prot_g, "g"] }), _jsxs("span", { children: ["G: ", choice.macros.fat_g, "g"] })] }), onSelect && (_jsx("button", { onClick: onSelect, className: "w-full rounded-xl bg-emerald-600 py-3 text-white font-semibold hover:bg-emerald-700 transition-colors", children: "Confirmar substitui\u00E7\u00E3o" }))] }));
};
export const AlternativeCard = ({ choice, index, onSelect }) => {
    return (_jsxs("div", { className: "flex items-center justify-between rounded-xl bg-white border border-gray-200 p-4 hover:border-gray-300 hover:shadow-sm transition-all cursor-pointer", onClick: onSelect, children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "flex h-8 w-8 items-center justify-center rounded-full bg-gray-100 text-sm font-semibold text-gray-600", children: index + 1 }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-gray-900", children: choice.food }), _jsxs("p", { className: "text-sm text-gray-500", children: [choice.grams, "g \u2022 ", choice.kcal, " kcal"] })] })] }), choice.equivalence_error !== undefined && choice.equivalence_error <= 5 && (_jsx("span", { className: "text-xs text-emerald-600 font-medium", children: "\u2248 equivalente" })), _jsx("svg", { className: "h-5 w-5 text-gray-400", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 5l7 7-7 7" }) })] }));
};
export const EvidenceSection = ({ preview, full, userRole }) => {
    const [isExpanded, setIsExpanded] = useState(false);
    const items = isExpanded && full ? full : preview;
    return (_jsxs("div", { className: "rounded-xl bg-gray-50 p-4", children: [_jsxs("button", { onClick: () => setIsExpanded(!isExpanded), className: "flex w-full items-center justify-between text-left", children: [_jsx("span", { className: "text-sm font-medium text-gray-700", children: "\uD83D\uDCDA Baseado em evid\u00EAncias" }), _jsx("svg", { className: `h-4 w-4 text-gray-500 transition-transform ${isExpanded ? 'rotate-180' : ''}`, fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M19 9l-7 7-7-7" }) })] }), isExpanded && (_jsx("div", { className: "mt-4 space-y-3", children: items.map((evidence, idx) => (_jsxs("div", { className: "rounded-lg bg-white p-3 border border-gray-100", children: [_jsxs("p", { className: "font-medium text-gray-800 text-sm", children: [evidence.title, evidence.evidence_level && (_jsxs("span", { className: "ml-2 text-xs text-gray-500", children: ["(N\u00EDvel ", evidence.evidence_level, ")"] }))] }), _jsx("p", { className: "text-sm text-gray-600 mt-1", children: evidence.note }), userRole === 'nutritionist' && evidence.doi && (_jsxs("a", { href: `https://doi.org/${evidence.doi}`, target: "_blank", rel: "noopener noreferrer", className: "text-xs text-emerald-600 hover:underline mt-2 inline-block", children: ["DOI: ", evidence.doi] })), userRole === 'nutritionist' && evidence.full_reference && (_jsx("p", { className: "text-xs text-gray-400 mt-1 italic", children: evidence.full_reference }))] }, idx))) }))] }));
};
export const NoAlternativeView = ({ response, onContact }) => {
    return (_jsxs("div", { className: "rounded-2xl bg-amber-50 border border-amber-200 p-6 text-center", children: [_jsx("div", { className: "mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-amber-100", children: _jsx("svg", { className: "h-6 w-6 text-amber-600", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" }) }) }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: response.reason }), _jsx("p", { className: "text-gray-600 mb-4", children: response.action }), response.contact_cta && onContact && (_jsx("button", { onClick: onContact, className: "rounded-xl bg-amber-600 px-6 py-3 text-white font-semibold hover:bg-amber-700 transition-colors", children: "Falar com nutricionista" }))] }));
};
export const SubstitutionView = ({ response, userRole, onSelectChoice, onContact }) => {
    if (response.type === 'no_safe_alternative') {
        return _jsx(NoAlternativeView, { response: response, onContact: onContact });
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "text-center", children: [_jsxs("h2", { className: "text-xl font-bold text-gray-900", children: ["Substitui\u00E7\u00F5es para ", response.base_item.food] }), _jsxs("p", { className: "text-sm text-gray-500 mt-1", children: [response.base_item.meal, " \u2022 ", response.base_item.grams, "g original"] })] }), _jsx(BestChoiceCard, { choice: response.best_choice, baseFood: response.base_item.food, onSelect: onSelectChoice ? () => onSelectChoice(response.best_choice) : undefined }), response.alternatives.length > 0 && (_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-500 mb-3", children: "Outras op\u00E7\u00F5es" }), _jsx("div", { className: "space-y-2", children: response.alternatives.map((alt, idx) => (_jsx(AlternativeCard, { choice: alt, index: idx, onSelect: onSelectChoice ? () => onSelectChoice(alt) : undefined }, idx))) })] })), _jsx(EvidenceSection, { preview: response.evidence_preview, full: response.evidence_full, userRole: userRole }), _jsx("p", { className: "text-xs text-gray-400 text-center", children: response.disclaimer }), userRole === 'nutritionist' && (_jsxs("div", { className: "rounded-lg bg-gray-100 p-3 text-xs text-gray-500", children: [_jsx("p", { children: _jsx("strong", { children: "Auditoria:" }) }), _jsxs("p", { children: ["Plano: ", response.plan_version, " | Policy: ", response.policy_version] }), _jsxs("p", { children: ["Request: ", response.request_id] }), _jsxs("p", { children: ["M\u00E9todo: ", response.audit.calculation_method] })] }))] }));
};
export const SubstitutionModal = ({ isOpen, onClose, response, userRole, onSelectChoice, onContact }) => {
    if (!isOpen || !response)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-50 bg-black/50 flex items-end sm:items-center justify-center", children: _jsxs("div", { className: "w-full sm:max-w-lg bg-white rounded-t-3xl sm:rounded-2xl max-h-[90vh] overflow-y-auto", children: [_jsxs("div", { className: "sticky top-0 bg-white border-b border-gray-100 p-4 flex items-center justify-between", children: [_jsx("h2", { className: "font-semibold text-gray-900", children: "Substitui\u00E7\u00E3o" }), _jsx("button", { onClick: onClose, className: "rounded-full p-2 hover:bg-gray-100", children: _jsx("svg", { className: "h-5 w-5 text-gray-500", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l12 12" }) }) })] }), _jsx("div", { className: "p-6", children: _jsx(SubstitutionView, { response: response, userRole: userRole, onSelectChoice: onSelectChoice, onContact: onContact }) })] }) }));
};
export default SubstitutionView;
