import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useRegistrationStore } from '../store/registrationStore';
import { Upload, Palette } from 'lucide-react';
import { cn } from '../../../components/ui/Stepper';
export const BrandingStep = () => {
    const { branding, updateBranding, nextStep, prevStep } = useRegistrationStore();
    // const fileInputRef = useRef<HTMLInputElement>(null); // Removido pois não é utilizado
    const handleColorChange = (e) => {
        updateBranding({ primaryColor: e.target.value });
    };
    const handleFileUpload = (field) => (e) => {
        const file = e.target.files?.[0];
        if (file) {
            // Create local URL for preview
            const url = URL.createObjectURL(file);
            updateBranding({ [field]: url });
        }
    };
    // Helper component for file upload box
    const UploadBox = ({ label, field, value }) => (_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-stone-600 block", children: label }), _jsxs("div", { className: "relative group cursor-pointer", children: [_jsx("input", { type: "file", accept: "image/*", className: "absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10", onChange: handleFileUpload(field) }), _jsx("div", { className: cn("h-32 rounded-xl border-2 border-dashed flex flex-col items-center justify-center transition-all bg-stone-50", value ? "border-emerald-400 bg-emerald-50" : "border-stone-200 group-hover:border-emerald-300"), children: value ? (_jsxs("div", { className: "relative w-full h-full p-2", children: [_jsx("img", { src: value, alt: label, className: "w-full h-full object-contain rounded-lg" }), _jsx("div", { className: "absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity rounded-lg", children: _jsx("span", { className: "text-white text-xs font-medium bg-black/50 px-2 py-1 rounded", children: "Alterar" }) })] })) : (_jsxs(_Fragment, { children: [_jsx(Upload, { className: "w-6 h-6 text-stone-400 mb-2 group-hover:text-emerald-500 transition-colors" }), _jsx("span", { className: "text-xs text-stone-500 font-medium", children: "Clique para upload" })] })) })] })] }));
    return (_jsxs("div", { className: "animate-in fade-in slide-in-from-right-4 duration-500 space-y-8", children: [_jsxs("div", { className: "bg-blue-50 border border-blue-100 rounded-lg p-4 text-sm text-blue-800 flex gap-2", children: [_jsx(SparklesIcon, { className: "w-5 h-5 flex-shrink-0" }), _jsx("p", { children: "Essas informa\u00E7\u00F5es personalizam todo o sistema. Seus pacientes ver\u00E3o sua marca, suas cores e sua foto." })] }), _jsxs("section", { className: "space-y-6", children: [_jsxs("h3", { className: "flex items-center gap-2 text-lg font-semibold text-stone-800 border-b border-stone-100 pb-2", children: [_jsx(Palette, { className: "w-5 h-5 text-emerald-500" }), "Identidade Visual"] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsx(UploadBox, { label: "Sua Foto", field: "photo", value: branding.photo }), _jsx(UploadBox, { label: "Logo da Cl\u00EDnica", field: "logo", value: branding.logo }), _jsx(UploadBox, { label: "Marca d'\u00E1gua (Relat\u00F3rios)", field: "watermark", value: branding.watermark })] }), _jsxs("div", { className: "pt-4", children: [_jsx("label", { className: "text-sm font-medium text-stone-600 block mb-3", children: "Cor Principal do Sistema" }), _jsxs("div", { className: "flex items-center gap-4 p-4 border border-stone-200 rounded-xl bg-white", children: [_jsx("input", { type: "color", value: branding.primaryColor, onChange: handleColorChange, className: "w-12 h-12 rounded cursor-pointer border-0 p-0" }), _jsxs("div", { className: "flex-1", children: [_jsxs("p", { className: "text-sm font-medium text-stone-900", children: ["Cor Selecionada: ", _jsx("span", { className: "uppercase font-mono text-stone-500", children: branding.primaryColor })] }), _jsx("p", { className: "text-xs text-stone-400", children: "Usada em bot\u00F5es, destaques e gr\u00E1ficos." })] }), _jsx("div", { className: "px-4 py-2 rounded-lg text-white text-sm font-medium shadow-sm transition-transform hover:scale-105", style: { backgroundColor: branding.primaryColor }, children: "Bot\u00E3o Exemplo" })] })] })] }), _jsxs("div", { className: "flex justify-between pt-6", children: [_jsx("button", { onClick: prevStep, className: "px-6 py-3 text-stone-600 font-medium hover:bg-stone-100 rounded-xl transition-all", children: "Voltar" }), _jsx("button", { onClick: nextStep, className: "px-8 py-3 bg-emerald-600 text-white rounded-xl font-medium hover:bg-emerald-700 transition-all shadow-lg hover:shadow-emerald-500/20", children: "Pr\u00F3ximo: Pagamento" })] })] }));
};
function SparklesIcon({ className }) {
    return (_jsx("svg", { className: className, fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 3.214L13 21l-2.286-6.857L5 12l5.714-3.214z" }) }));
}
