import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useRegistrationStore } from '../store/registrationStore';
import { useNavigate } from 'react-router-dom';
import { CheckCircle, Users, DollarSign, ArrowRight } from 'lucide-react';
export const FinancialSummaryStep = () => {
    const { reset } = useRegistrationStore();
    const navigate = useNavigate();
    // Reset store on unmount or after leaving, but here we want to clear it when going to dashboard
    const handleGoToDashboard = () => {
        reset();
        navigate('/acesso-nutricionista'); // Or direct to dashboard if we had real auth token flow set up
    };
    return (_jsxs("div", { className: "animate-in fade-in zoom-in-95 duration-700 text-center space-y-8", children: [_jsxs("div", { className: "flex flex-col items-center justify-center", children: [_jsx("div", { className: "w-20 h-20 bg-emerald-100 rounded-full flex items-center justify-center mb-6 animate-bounce", children: _jsx(CheckCircle, { className: "w-10 h-10 text-emerald-600" }) }), _jsx("h2", { className: "text-3xl font-serif font-bold text-stone-900 mb-2", children: "Tudo pronto!" }), _jsx("p", { className: "text-stone-500 max-w-md mx-auto", children: "Sua conta foi criada e seu ambiente j\u00E1 est\u00E1 configurado com sua identidade visual." })] }), _jsxs("div", { className: "bg-white rounded-2xl shadow-xl border border-stone-100 overflow-hidden max-w-lg mx-auto", children: [_jsxs("div", { className: "bg-stone-50 px-6 py-4 border-b border-stone-100 flex justify-between items-center", children: [_jsx("span", { className: "text-sm font-semibold text-stone-600 uppercase tracking-wider", children: "Resumo Financeiro" }), _jsx("span", { className: "px-2 py-1 bg-emerald-100 text-emerald-700 text-xs font-bold rounded uppercase", children: "Premium Ativo" })] }), _jsxs("div", { className: "p-8 grid grid-cols-2 gap-8 divide-x divide-stone-100", children: [_jsxs("div", { className: "text-center space-y-2", children: [_jsx("div", { className: "flex justify-center text-stone-400 mb-2", children: _jsx(Users, { className: "w-6 h-6" }) }), _jsx("div", { className: "text-3xl font-bold text-stone-900", children: "0" }), _jsx("div", { className: "text-sm text-stone-500", children: "Pacientes Ativos" })] }), _jsxs("div", { className: "text-center space-y-2", children: [_jsx("div", { className: "flex justify-center text-stone-400 mb-2", children: _jsx(DollarSign, { className: "w-6 h-6" }) }), _jsx("div", { className: "text-3xl font-bold text-stone-900", children: "R$ 0,00" }), _jsx("div", { className: "text-sm text-stone-500", children: "Custo Estimado/m\u00EAs" })] })] }), _jsx("div", { className: "bg-emerald-50/50 p-4 text-sm text-emerald-800 border-t border-emerald-100", children: "\u201CVoc\u00EA s\u00F3 paga por pacientes com acesso liberado.\u201D" })] }), _jsxs("div", { className: "pt-4 space-y-3", children: [_jsxs("button", { onClick: handleGoToDashboard, className: "w-full max-w-sm mx-auto py-4 bg-emerald-600 text-white rounded-xl font-bold text-lg hover:bg-emerald-700 shadow-lg hover:shadow-emerald-500/30 transition-all flex items-center justify-center gap-2", children: ["Ir para o Painel", _jsx(ArrowRight, { className: "w-5 h-5" })] }), _jsx("button", { onClick: handleGoToDashboard, className: "block w-full max-w-sm mx-auto py-3 text-stone-500 hover:text-stone-700 text-sm font-medium transition-colors", children: "Cadastrar primeiro paciente" })] })] }));
};
