import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const LoginScreen = ({ onLogin }) => {
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-br from-emerald-50 via-white to-teal-50 flex items-center justify-center p-4", children: _jsxs("div", { className: "max-w-md w-full bg-white p-8 rounded-2xl shadow-xl border border-stone-200 text-center space-y-8", children: [_jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "w-28 h-28 mx-auto mb-4 rounded-full overflow-hidden border-4 border-emerald-200 shadow-lg bg-gradient-to-br from-emerald-100 to-teal-100 flex items-center justify-center", children: _jsx("img", { src: "/images/dra-vanessa.jpg?v=1", alt: "Dra. Vanessa Bahia", className: "w-full h-full object-cover", onError: (e) => {
                                    const target = e.target;
                                    target.style.display = 'none';
                                    if (target.parentElement) {
                                        target.parentElement.innerHTML = '<span class="text-4xl">👩‍⚕️</span>';
                                    }
                                } }) }), _jsx("h1", { className: "font-serif text-3xl font-bold text-stone-900", children: "Dra. Vanessa Bahia" }), _jsx("p", { className: "text-emerald-600 text-sm font-medium", children: "Seu cuidado di\u00E1rio" }), _jsx("p", { className: "text-stone-400 text-xs italic", children: "Nutrindo corpo e mente, com reflex\u00E3o e tempero" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("button", { onClick: () => onLogin('client'), className: "w-full p-4 border-2 border-stone-100 rounded-xl hover:border-emerald-400 hover:bg-emerald-50 transition-all group text-left flex items-center gap-4", children: [_jsx("div", { className: "text-3xl bg-white p-2 rounded-full shadow-sm group-hover:scale-110 transition-transform", children: "\uD83D\uDC64" }), _jsxs("div", { children: [_jsx("div", { className: "font-bold text-stone-800", children: "Sou Paciente" }), _jsx("div", { className: "text-xs text-stone-500", children: "Acessar meu plano nutricional integrativo" })] })] }), _jsxs("button", { onClick: () => onLogin('professional'), className: "w-full p-4 border-2 border-stone-100 rounded-xl hover:border-teal-700 hover:bg-teal-50 transition-all group text-left flex items-center gap-4", children: [_jsx("div", { className: "text-3xl bg-white p-2 rounded-full shadow-sm group-hover:scale-110 transition-transform", children: "\uD83D\uDC69\u200D\u2695\uFE0F" }), _jsxs("div", { children: [_jsx("div", { className: "font-bold text-stone-800", children: "Sou Nutricionista" }), _jsx("div", { className: "text-xs text-stone-500", children: "Gerenciar pacientes com abordagem integrativa" })] })] })] }), _jsxs("div", { className: "pt-4 border-t border-stone-100", children: [_jsx("p", { className: "text-xs text-stone-400", children: "Cuidando de voc\u00EA por inteiro" }), _jsx("p", { className: "text-[10px] text-stone-300 mt-2", children: "v2.0 - Nutri\u00E7\u00E3o Integrativa" })] })] }) }));
};
export default LoginScreen;
